[package]
name = "nostr"
version = "0.17.0"
edition = "2021"
description = "Rust implementation of the Nostr protocol."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "protocol", "sdk", "rust"]

[features]
default = ["all-nips", "base"]
blocking = ["reqwest?/blocking"]
base = ["dep:log", "dep:once_cell", "dep:regex", "dep:serde", "dep:serde_json", "dep:url"]
vanity = ["nip19"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip13", "nip19", "nip26"]
nip04 = ["dep:aes", "dep:base64", "dep:cbc"]
nip05 = ["dep:reqwest", "dep:serde_json"]
nip06 = ["dep:bip39"]
nip11 = ["dep:reqwest", "dep:serde", "dep:url"]
nip13 = ["dep:log"]
nip19 = ["dep:serde"]
nip26 = []

[dependencies]
aes = { version = "0.8", optional = true }
base64 = { version = "0.21", optional = true }
bip39 = { version = "1.0", optional = true }
bitcoin = { version = "0.29", features = ["rand", "serde"] }
cbc = { version = "0.1", features = ["alloc"], optional = true }
log = { version = "0.4", optional = true }
once_cell = { version = "1", optional = true }
regex = { version = "1.7", optional = true }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = "1.0"
url = { version = "2", features = ["serde"], optional = true }
uuid = {version = "1.2.2", features = ["v4"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = [ "stdweb", "inaccurate" ] }

[dev-dependencies]
csv = "1.1.5"
env_logger = "0.10.0"
num_cpus = "1.15.0"
tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }

[[example]]
name = "keys"
required-features = ["nip19"]

[[example]]
name = "metadata"
required-features = ["base"]

[[example]]
name = "tweet"
required-features = ["base"]

[[example]]
name = "nip04"
required-features = ["base", "nip04"]

[[example]]
name = "nip05"
required-features = ["nip05", "blocking"]

[[example]]
name = "nip06"
required-features = ["nip06"]

[[example]]
name = "nip09"
required-features = ["base", "nip19"]

[[example]]
name = "nip11"
required-features = ["nip11", "blocking"]

[[example]]
name = "nip13"
required-features = ["base", "nip13"]

[[example]]
name = "nip19"
required-features = ["base", "nip19"]

[[example]]
name = "vanity"
required-features = ["vanity"]
